// Assets/Editor/BlendshapeCurveRestorer.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

public class BlendshapeCurveRestorer : EditorWindow
{
    private AnimationClip sourceClip;
    private string saveSuffix = "_restored";
    private Vector2 scrollPos;

    // 你已经提供的候选列表（可在窗口里编辑或改成从文件加载）
    // private List<string> morphCandidates = new List<string>(){};
    private List<string> morphCandidates = new List<string>
    {
        "まばたき","笑い",
        "あ","い","う","え","お","あ２","ん","▲","∧","□","真面目","困る","にこり","怒り","上","下","前","眉頭左","眉頭右","ウィンク","ウィンク右","ウィンク２","ｳｨﾝｸ２右","なごみ","はぅ","びっくり","じと目","ｷﾘｯ","はちゅ目","はちゅ目縦潰れ","はちゅ目横潰れ","瞳小","瞳縦潰れ","恐ろしい子！","ワ","ω","ω□","にやり","にやり２","にっこり","ぺろっ","てへぺろ","てへぺろ２","口角上げ","口角下げ","口横広げ","歯無し上","歯無し下","照れ","涙","輪郭","星目","はぁと", "ジト目", "はちゆ目", "はう", "ハイライト消し", "えー" ,"はんっ!" ,"べろっ","てへべろ" ,"青ざめ","左上","右上", "左下", "右下" ,"不機嫌","眉上げ", "赤面","猫目","がーん","カメラ目","瞳縦","ウィンクＬ", "への字" , "垂れ左ウインク","垂れウインク","垂れジト目" ,"垂れなごみ" ,"垂れ笑顔","垂れ目まばたき" ,"垂れ目","右もぐもぐ" ,"左もぐもぐ" ,"もぐもぐ" ,"下睫毛消" ,"上睫毛消" ,"舌無し" ," 口横狭め","右口横狭め" ,"左口横狭め", "右口横広げ" ,"左口横広げ" ,"右口角下げ" ,"左口角下げ" ,"右口角上げ" ,"左口角上げ" ,"八重歯右" ,"八重歯左" ,"д","泣き黒子" ,"おお" ,"いい" ,"ああ" ,"左眉上げ","左眉不機嫌",
        "左眉怒り",
        "左眉困り",
        "右眉上げ",
        "右眉不機嫌",
        "右眉怒り",
        "右眉困り",
        "怒り右",
        "怒り左",
        "困る右",
        "困る左",
        "怪訝右",
        "怪訝左",
        "平行",
        "近",
        "離",
        "短",
        "前",
        "眉頭",
        "左眉頭",
        "右眉頭",
        "眉粗",
        "細",
        "太",
        "ハンサム",
        "光下",
        "メガネ",
        "みっぱい",
        "じしん",
        "LightUp",
        "LightOff",
        "LightBlink",
        "LightBS",
        "広い",
        "v_aa", "v_e", "v_ee", "v_ih", "v_oh", "v_ou", "v_sil", "v_ch", "v_dd", "v_ff", "v_kk", "v_nn", "v_pp", "v_rr", "v_ss", "v_th", "LeftBlink", "RightBlink", "Blink", "vrc.v_aa", "vrc.v_e", "vrc.v_ee", "vrc.v_ih", "vrc.v_oh", "vrc.v_ou", "vrc.v_sil", "vrc.v_ch", "vrc.v_dd", "vrc.v_ff", "vrc.v_kk", "vrc.v_nn", "vrc.v_pp", "vrc.v_rr", "vrc.v_ss", "vrc.v_th", "aa", "e", "ee", "ih", "oh", "ou", "sil", "ch", "dd", "ff", "kk", "nn", "pp", "rr", "ss", "th",
        "A", "I", "O", "U","E", "SIL", "CH", "DD", "FF", "KK", "NN", "PP", "RR", "SS", "TH", "Blink_L", "Blink_R", "Blink", "A",  "I", "O",  "SIL", "CH", "DD", "FF", "KK", "NN", "PP", "RR", "SS", "TH", "A", "I", "O",  "SIL", "CH", "DD", "FF", "KK", "NN", "PP", "RR", "SS", "TH",  "CasualSlacks",
        "BlinkLeft","BlinkRight","Blink_l", "Blink_r","Blinkleft","Blinkright", "Wink_L","Wink_R","Wink_l","Wink_r","WinkLeft","WinkRight",
        "eye_close_L" ,"eye_close_R","eye_close_l","eye_close_r",
  "Chartreuse Green",
  "Emerald Green",
  "Oriental Blue",
  "Carrot Orange",
  "Golden Yellow",
  "Chinese Red",
  "Naples Yellow",
  "Billiard Green",
  "Peacock Green",
  "Forest Green",
  "Malachite Green",
  "Mandarin Orange",
  "Midnight Blue",
  "Ivy Green",
  "Apple Green",
  "Yellow Ocher",
  "Olive Green",
  "Canary Yellow",
  "CuffChoker",
  "Cream Yellow",
  "Cochineal Red",
  "Cobalt Green",
  "Sunglasses_lens",
  "Cerulean Blue",
  "Turquoise Blue",
  "Charcoal Grey",
  "Butterfly_shirt",
  "Burnt Umber",
  "Burnt Sienna",
  "Peacock Blue",
  "Prussian Blue",
  "Garter_boots",
  "BowTie",
  "Iron Blue",
  "Ash Grey",
  "Ultramarine Blue",
  "Ecru Beige",
  "Olive Drab",
  "Old Rose",
  "Chrome Yellow",
  "Grass Green",
  "Cocoa Brown",
  "Cobalt Blue",
  "Coral Red",
  "Saxe Blue",
  "Sunglasses_rim",
  "Salmon Pink",
  "Signal Red",
  "Silver Grey",
  "Jaune Brillant",
  "Steel Grey",
  "Snow White",
  "Slate Grey",
  "SailorSwimsuit",
  "Cherry Pink",
  "Teardrop",
  "Navy Blue",
  "Burgundy",
  "Heliotrope",
  "Horizon Blue",
  "Bottle Green",
  "Marigold",
  "Mint Green",
  "Lime_green",
  "Lamp Black",
  "Leaf Green",
  "Lemon Yellow",
  "Do not look at me",
  "Clothing",
  "Apricot",
  "Arlvit",
  "Wistaria",
  "Wink 2 Right",
  "Orange",
  "CufflinkButton",
  "Cardigan",
  "Shell Pink",
  "Sea Green",
  "Sky Grey",
  "Sky Blue",
  "Scarlet",
  "Stockings",
  "Strawberry",
  "Chocolate",
  "Teardrop",
  "Tomato Red",
  "Nile Blue",
  "Nail Pink",
  "Violet",
  "BunnyEars",
  "Vermilion",
  "Pearl Grey",
  "Headset",
  "BabyDoll",
  "Baby Pink",
  "Baby Blue",
  "Poppy Red",
  "Marine Blue",
  "Yamazanadu",
  "Ruby Red",
  "Raincoat",
  "Raw Umber",
  "Raw Sienna",
  "Rose Grey",
  "Rose Pink",
  "Rose Red",
  "Wine Red",
  "Brown",
  "ShortPants",
  "Ivory",
  "Earring",
  "Wink Right",
  "Wink 2",
  "Orange",
  "Oechid",
  "Casual",
  "Carmine",
  "Control",
  "Crystals",
  "Sunglasses",
  "Jacket",
  "Scout",
  "Sneakers",
  "Slacks",
  "Terracotta",
  "Boxers",
  "SweatShirt",
  "Necklace",
  "HighHeelShoes",
  "Highlight",
  "Butterfly",
  "Hyacinth",
  "Viridian",
  "Bra",
  "BeltLoops",
  "InnerButton",
  "Lilac",
  "Lavender",
  "Leotard",
  "Leghorn",
  "Shirt",
  "Dress",
  "Venus",
  "HorrorChild",
  "BowTie",
  "T-shirt",
  "Garter",
  "Breasts",
  "LeatherShoes",
  "Socks",
  "Navy_blue",
  "Shrink",
  "Wristband",
  "Brown",
  "Gloves",
  "Reddish_brown",
  "Smile",
  "CatEars",
  "Grey",
  "Fool",
  "Flutter",
  "Surprised",
  "SlenderBody",
  "Blink",
  "WiderBody",
  "Purple",
  "Sideburn",
  "Amber",
  "Armor",
  "Yellow",
  "Wink",
  "Waist",
  "Apron",
  "Olive",
  "Orange",
  "Overcoat",
  "ColorVariations",
  "Cap",
  "Crotch",
  "Green",
  "Groove",
  "Group",
  "Sandals",
  "Siesta",
  "Shorts",
  "Jean",
  "SkirtSide",
  "Skirt",
  "Scarf",
  "Spectrum",
  "Sports",
  "Slime",
  "Slippers",
  "Center",
  "Sweater",
  "Chain",
  "Vest",
  "Twintail",
  "Cards",
  "Necktie",
  "Buckle",
  "Bunny",
  "Pajamas",
  "Pansy",
  "Pantyhose",
  "Purple",
  "Blouse",
  "Brown",
  "Black",
  "Briefs",
  "Blazer",
  "Bronze",
  "Blond",
  "Brooch",
  "Beige",
  "White",
  "Bordeaux",
  "Magenta",
  "Scarf",
  "Maroon",
  "Tape",
  "Sideburn",
  "Rivet",
  "Braid",
  "RoundedTips",
  "ParentNode",
  "Hatsune Miku",
  "PowerUp",
  "ShortPants",
  "ReflectionLower",
  "Shiki Eiki",
  "PreventSagging",
  "Anger",
  "ControlNode",
  "CostumeColor",
  "PreventSagging",
  "Bust_guard",
  "ChainMovement",
  "HairColor",
  "Swirl",
  "Mad",
  "Cross Star",
  "Oiled",
  "Translucent",
  "Zip",
  "Bandage",
  "Jacket",
  "Dummy",
  "Bunny",
  "Oh no!",
  "Antenna",
  "Clothes",
  "Cry",
  "Coat",
  "Pigtail",
  "Roar",
  "Gloom",
  "Yellow",
  "Kimono",
  "FemaleNinja",
  "Underwear",
  "Stare",
  "Suit",
  "Mechanism",
  "TehHeh",
  "Tears",
  "Calm",
  "Coloring",
  "Confuse",
  "Lick",
  "Cheerful",
  "Wrinkle",
  "Grin",
  "Heart",
  "Heart",
  "Hachu",
  "Pants",
  "Scarlet",
  "Sleepy",
  "Fuun",
  "Lick",
  "Hat",
  "Eyelash",
  "Swimsuit",
  "Green",
  "Glasses",
  "SummerKimono",
  "Ring",
  "PreventSagging",
  "Access",
  "Duck",
  "Antenna",
  "IhHiHi",
  "Ears",
  "Leg",
  "Edge",
  "Cuff",
  "Khaki",
  "Girl",
  "Gloom",
  "Grey",
  "Cork",
  "Coat",
  "Cord",
  "Samba",
  "Cyan",
  "Shirt",
  "Seam",
  "Skirt",
  "Suit",
  "Trousers",
  "Set",
  "Sepia",
  "Center",
  "Tights",
  "Dress",
  "Back",
  "Badge",
  "Band",
  "Pants",
  "Part",
  "Hip",
  "HighHeelShoes",
  "Bikini",
  "Earring",
  "Pink",
  "Peach",
  "Frill",
  "Brim",
  "Blue",
  "Blue",
  "Brooch",
  "Boots",
  "Belt",
  "Button",
  "Body",
  "Bottom",
  "Bone",
  "Really",
  "Cloak",
  "Meiko",
  "Maid",
  "Glasses",
  "Morph",
  "Mauve",
  "Ribbon",
  "Ring",
  "Red",
  "Rose",
  "UpperBody",
  "Chin",
  "LowerBody",
  "Bad mood",
  "Double",
  "IndexFinger",
  "Taper",
  "Izayoi",
  "Sunflower",
  "FemaleWarrior",
  "Together",
  "Koakuma",
  "Onozuka",
  "Yuyuko",
  "Sad",
  "ChangeColor",
  "CasualClothes",
  "Fasteners",
  "Pink",
  "SwallowTailCoat",
  "Serious",
  "Kanako",
  "Move",
  "String",
  "Tighten",
  "Bandage",
  "Green",
  "EarMovement",
  "Bust_support",
  "ChangeColor",
  "Clothing",
  "Saigyouji",
  "Spread",
  "Red",
  "ChainMovement",
  "Pale",
  "Blue",
  "Leather",
  "RubberBand",
  "Slant",
  "Jacket",
  "Leotard",
  "Wow",
  "Mark",
  "Glue",
  "Slurping",
  "Well",
  "Leg",
  "Blue",
  "Red",
  "Jaw",
  "Arm",
  "Uueh",
  "Collar",
  "e-",
  "Ugh",
  "Shoes",
  "Black",
  "Right",
  "Left",
  "Tips",
  "White",
  "Tooth",
  "Sushi",
  "LowerClothes",
  "Sleeve",
  "Falcon",
  "Droopy",
  "Toe",
  "Slant",
  "TehHeh",
  "Thorn",
  "None",
  "None",
  "Lick",
  "Smile",
  "Oiled",
  "Haa",
  "Close><",
  "Knee",
  "Elbow",
  "Inflate",
  "Grow",
  "TongueOut",
  "Lick",
  "Cruciform",
  "Eee",
  "Off",
  "Looseness",
  "Tan",
  "Hair",
  "Buff",
  "HighHeelShoes",
  "Spotted",
  "Boots",
  "Bra",
  "Behh",
  "Miku",
  "Leotard",
  "Lower",
  "Raise",
  "Upper",
  "Coat",
  "Lower",
  "Lower",
  "Underwear",
  "Chin",
  "Dissatisfied",
  "Eyes",
  "MiddleFinger",
  "Red",
  "Double",
  "IndexFinger",
  "Attachment",
  "Bodyu",
  "Bodyl",
  "Tips",
  "Yasaka",
  "Yagokoro",
  "Yakumo",
  "Hexagon",
  "FrontHair",
  "Yuugi",
  "Hide",
  "RightHand",
  "Sunrise",
  "Amazement",
  "Calm",
  "Sakuya",
  "Bite",
  "Apparatus",
  "Rotation",
  "Troubled",
  "Sadness",
  "Base",
  "Wider",
  "FemalePriest",
  "WiseWoman",
  "Learning",
  "LittleFinger",
  "Komachi",
  "LeftHand",
  "Hat",
  "Yuuka",
  "Widen",
  "Behind",
  "Angry",
  "GetAngry",
  "Emotion",
  "Grieving",
  "Warrior",
  "Gloves",
  "Wrist",
  "Ring",
  "Shake",
  "New",
  "Color",
  "Hoshiguma",
  "Princess",
  "Deep",
  "Deep",
  "Material",
  "Blush",
  "Pink",
  "ChangeColoredShapes",
  "SideHair",
  "Orange",
  "Crystals",
  "Swimsuit",
  "Eirin",
  "Cry",
  "SummerKimono",
  "Puffy Eyes",
  "Measurement",
  "Collapse",
  "Grey",
  "None",
  "Blush",
  "Physics",
  "Narrowly",
  "White",
  "Byakuren",
  "Eyebrow",
  "Eyebrow",
  "Serious",
  "Glasses",
  "Kimono",
  "Wear",
  "Pupil",
  "Pupil",
  "Move",
  "Blink Happy",
  "Laugh",
  "Thinner",
  "Thin Eyebrows",
  "Gentleman",
  "Navy_blue",
  "Scroll",
  "Scarlet",
  "Gun",
  "Braids",
  "Shrink",
  "Locations",
  "Meiling",
  "Suit",
  "Cordon",
  "Stage",
  "Brown",
  "Leaves",
  "Thinner",
  "RingFinger",
  "Clothes",
  "Costume",
  "Expressions",
  "Wristband",
  "Aux",
  "Brown",
  "Thumb",
  "Angle",
  "Expand",
  "Antenna",
  "Adjustment",
  "Pastie",
  "WiseMan",
  "Red",
  "Ankle",
  "MilitaryCap",
  "MilitaryUniform",
  "LightClothing",
  "Lightweight",
  "Contour",
  "Append",
  "Transparent",
  "Connection",
  "Parts",
  "Parts",
  "Metal",
  "Clavicle",
  "Open",
  "Dark",
  "Dark",
  "Hide",
  "Blue green",
  "LeatherShoes",
  "Socks",
  "Kazami",
  "Accessory",
  "Reddish_brown",
  "Yellow",
  "Black",
  "Grey",
  "IK",
  "Oiled",
  "Glaring",
  "Double",
  "Both",
  "Star",
  "Ear",
  "ω□",
  "~",
  "ー",
  "ω",
  "※",
  "∧",
  "□",
  "▲",
  "○",
  "●",
  ">",
  "<",
  "",
  "@",
  "A",
  "I",
  "E",
  "O",
  "Hmm",
  "",
  "",
  "no",
  "FacialExpression",
  "Beh",
  "Body",
  "wo",
  "Higher",
  "Lower",
  "Wa",
  "*",
  "One",
  "Upper",
  "Lower",
  "Casual",
  "Middle",
  "Circle",
  "Breasts",
  "Two",
  "Other",
  "Attachment",
  "Extend",
  "Location",
  "Body",
  "Origin",
  "Tip",
  "Light",
  "Bunny",
  "Six",
  "Inside",
  "Circle",
  "Out",
  "Part",
  "Front",
  "Sword",
  "Half",
  "Thick",
  "Mouth",
  "Right",
  "Lips",
  "Vertical",
  "Type",
  "Category",
  "Change",
  "Outside",
  "Big",
  "Wide",
  "Center",
  "Back",
  "Character",
  "Gem",
  "Small",
  "Tip",
  "Butt",
  "Tail",
  "Left",
  "Difference",
  "Book",
  "Band",
  "Wide",
  "Wide",
  "Force",
  "ColorScheme",
  "Back",
  "Angry",
  "Evil",
  "Love",
  "Return",
  "Hand",
  "Expand",
  "TieFasten",
  "Finger",
  "Twist",
  "Shake",
  "Color",
  "Star",
  "Clothes",
  "Book",
  "Blush",
  "Base",
  "Pink",
  "Cherry",
  "Thorn",
  "Side",
  "Teeth",
  "Strand",
  "Water",
  "Sweat",
  "Tears",
  "Tips",
  "Nothing",
  "Swallow",
  "Object",
  "Narrow",
  "Ball",
  "Bare",
  "White",
  "Eye",
  "Eyebrow",
  "Eye",
  "Wear",
  "Pupil",
  "Stone",
  "End",
  "LOL",
  "Marks",
  "Muscle",
  "Hong",
  "String",
  "Yukari",
  "Thin",
  "Connection",
  "Net",
  "Green",
  "Vertical",
  "Location",
  "Wing",
  "Ears",
  "Hijiri",
  "Skin",
  "Elbow",
  "Shoulder",
  "Back",
  "Breast",
  "Shin",
  "Armpit",
  "Arm",
  "Waist",
  "Belly",
  "Thigh",
  "Tongue",
  "Lick",
  "Dance",
  "Color",
  "Flower",
  "Brown",
  "Leaf",
  "Hollyhock",
  "Lotus",
  "Thin",
  "Ran",
  "Rainbow",
  "Snake",
  "Butterfly",
  "Sleeve",
  "Increase",
  "Bare",
  "LowerClothes",
  "Collar",
  "Tooth",
  "Parent",
  "Horn",
  "Small",
  "Pastie",
  "Red",
  "Leg",
  "Dance",
  "Body",
  "Army",
  "Axis",
  "Circles",
  "Transparent",
  "Over",
  "Part",
  "Cone",
  "Chain",
  "ChainStraps",
  "Open",
  "Interval",
  "Hide",
  "Blue",
  "Not",
  "Leather",
  "Shoes",
  "Top",
  "Cheek",
  "Head",
  "Jaw",
  "Face",
  "Type",
  "Neck",
  "Bone",
  "Hair",
  "Demon",
  "Black",
  "!",
  "+",
  "-",
  "/",
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "?",
  "A",
  "B",
  "C",
  "D",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "_",
  "a",
  "b",
  "c",
  "d",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z"

    };

    // private Dictionary<string, string> morphAlias = new Dictionary<string, string>{};
    private Dictionary<string, string> morphAlias = new Dictionary<string, string>
    {
        ["CasualSlacks"] = "カジュアルスラックス",
        ["Chartreuse Green"] = "シャトルーズグリーン",
        ["Emerald Green"] = "エメラルドグリーン",
        ["Oriental Blue"] = "オリエンタルブルー",
        ["Carrot Orange"] = "キャロットオレンジ",
        ["Golden Yellow"] = "ゴールデンイエロー",
        ["Chinese Red"] = "チャイニーズレッド",
        ["Naples Yellow"] = "ネープルスイエロー",
        ["Billiard Green"] = "ビリヤードグリーン",
        ["Peacock Green"] = "ピーコックグリーン",
        ["Forest Green"] = "フォレストグリーン",
        ["Malachite Green"] = "マラカイトグリーン",
        ["Mandarin Orange"] = "マンダリンオレンジ",
        ["Midnight Blue"] = "ミッドナイトブルー",
        ["Ivy Green"] = "アイビーグリーン",
        ["Apple Green"] = "アップルグリーン",
        ["Yellow Ocher"] = "イエローオーカー",
        ["Olive Green"] = "オリーブグリーン",
        ["Canary Yellow"] = "カナリーイエロー",
        ["CuffChoker"] = "カフスチョーカー",
        ["Cream Yellow"] = "クリームイエロー",
        ["Cochineal Red"] = "コチニールレッド",
        ["Cobalt Green"] = "コバルトグリーン",
        ["Sunglasses_lens"] = "サングラスレンズ",
        ["Cerulean Blue"] = "セルリアンブルー",
        ["Turquoise Blue"] = "ターコイズブルー",
        ["Charcoal Grey"] = "チャコールグレー",
        ["Butterfly_shirt"] = "バタフライショツ",
        ["Burnt Umber"] = "バーントアンバー",
        ["Burnt Sienna"] = "バーントシェンナ",
        ["Peacock Blue"] = "ピーコックブルー",
        ["Prussian Blue"] = "プルシアンブルー",
        ["Garter_boots"] = "ガーターブーツ",
        ["BowTie"] = "蝶ネクタイ",
        ["Iron Blue"] = "アイアンブルー",
        ["Ash Grey"] = "アッシュグレー",
        ["Ultramarine Blue"] = "ウルトラマリン",
        ["Ecru Beige"] = "エクルベージュ",
        ["Olive Drab"] = "オリーブドラブ",
        ["Old Rose"] = "オールドローズ",
        ["Chrome Yellow"] = "クロムイエロー",
        ["Grass Green"] = "グラスグリーン",
        ["Cocoa Brown"] = "ココアブラウン",
        ["Cobalt Blue"] = "コバルトブルー",
        ["Coral Red"] = "コーラルレッド",
        ["Saxe Blue"] = "サックスブルー",
        ["Sunglasses_rim"] = "サングラスリム",
        ["Salmon Pink"] = "サーモンピンク",
        ["Signal Red"] = "シグナルレッド",
        ["Silver Grey"] = "シルバーグレー",
        ["Jaune Brillant"] = "ジョンブリアン",
        ["Steel Grey"] = "スチールグレー",
        ["Snow White"] = "スノーホワイト",
        ["Slate Grey"] = "スレートグレー",
        ["SailorSwimsuit"] = "セーラーミズギ",
        ["Cherry Pink"] = "チェリーピンク",
        ["Teardrop"] = "ティアドップ",
        ["Navy Blue"] = "ネイビーブルー",
        ["Burgundy"] = "バーガンディー",
        ["Heliotrope"] = "ヘリオトロープ",
        ["Horizon Blue"] = "ホリゾンブルー",
        ["Bottle Green"] = "ボトルグリーン",
        ["Marigold"] = "マリーゴールド",
        ["Mint Green"] = "ミントグリーン",
        ["Lime_green"] = "ライムグリーン",
        ["Lamp Black"] = "ランプブラック",
        ["Leaf Green"] = "リーフグリーン",
        ["Lemon Yellow"] = "レモンイエロー",
        ["Do not look at me"] = "こっちみんな",
        ["Clothing"] = "衣料品",
        ["Apricot"] = "アプリコット",
        ["Arlvit"] = "アールビット",
        ["Wistaria"] = "ウィスタリア",
        ["Wink 2 Right"] = "ウインク２右",
        ["Orange"] = "橙色",
        ["CufflinkButton"] = "カフスボタン",
        ["Cardigan"] = "カーディガン",
        ["Shell Pink"] = "シェルピンク",
        ["Sea Green"] = "シーグリーン",
        ["Sky Grey"] = "スカイグレー",
        ["Sky Blue"] = "スカイブルー",
        ["Scarlet"] = "緋色",
        ["Stockings"] = "ストッキング",
        ["Strawberry"] = "ストロベリー",
        ["Chocolate"] = "チョコレート",
        ["Tomato Red"] = "トマトレッド",
        ["Nile Blue"] = "ナイルブルー",
        ["Nail Pink"] = "ネールピンク",
        ["Violet"] = "バイオレット",
        ["BunnyEars"] = "バニーイヤー",
        ["Vermilion"] = "バーミリオン",
        ["Pearl Grey"] = "パールグレー",
        ["Headset"] = "ヘッドセット",
        ["BabyDoll"] = "ベビードール",
        ["Baby Pink"] = "ベビーピンク",
        ["Baby Blue"] = "ベビーブルー",
        ["Poppy Red"] = "ポピーレッド",
        ["Marine Blue"] = "マリンブルー",
        ["Yamazanadu"] = "ヤマザナドゥ",
        ["Ruby Red"] = "ルビーレッド",
        ["Raincoat"] = "レインコート",
        ["Raw Umber"] = "ローアンバー",
        ["Raw Sienna"] = "ローシェンナ",
        ["Rose Grey"] = "ローズグレー",
        ["Rose Pink"] = "ローズピンク",
        ["Rose Red"] = "ローズレッド",
        ["Wine Red"] = "ワインレッド",
        ["Brown"] = "茶",
        ["ShortPants"] = "半ズボン",
        ["Ivory"] = "アイボリー",
        ["Earring"] = "ピアス",
        ["Wink Right"] = "ウインク右",
        ["Wink 2"] = "ウインク２",
        ["Oechid"] = "オーキッド",
        ["Casual"] = "並",
        ["Carmine"] = "カーマイン",
        ["Control"] = "キャンセル",
        ["Crystals"] = "水晶",
        ["Sunglasses"] = "サングラス",
        ["Jacket"] = "ケット",
        ["Scout"] = "スカウター",
        ["Sneakers"] = "スニーカー",
        ["Slacks"] = "スラックス",
        ["Terracotta"] = "テラコッタ",
        ["Boxers"] = "トランクス",
        ["SweatShirt"] = "トレーナー",
        ["Necklace"] = "ネックレス",
        ["HighHeelShoes"] = "ヒル",
        ["Highlight"] = "ハイライト",
        ["Butterfly"] = "蝶",
        ["Hyacinth"] = "ヒヤシンス",
        ["Viridian"] = "ビリジアン",
        ["Bra"] = "ブラ",
        ["BeltLoops"] = "ベルト通し",
        ["InnerButton"] = "ボタンの中",
        ["Lilac"] = "ライラック",
        ["Lavender"] = "ラベンダー",
        ["Leotard"] = "レオ",
        ["Leghorn"] = "レグホーン",
        ["Shirt"] = "シャツ",
        ["Dress"] = "ドレス",
        ["Venus"] = "ヴィーナス",
        ["HorrorChild"] = "恐ろしい子",
        ["T-shirt"] = "T-シャツ",
        ["Garter"] = "ガーター",
        ["Breasts"] = "乳",
        ["LeatherShoes"] = "革靴",
        ["Socks"] = "靴下",
        ["Navy_blue"] = "紺色",
        ["Shrink"] = "縮小",
        ["Wristband"] = "袖口",
        ["Gloves"] = "手袋",
        ["Reddish_brown"] = "鳶色",
        ["Smile"] = "にこ",
        ["CatEars"] = "ねこみみ",
        ["Grey"] = "鼠色",
        ["Fool"] = "はんっ！",
        ["Flutter"] = "ひらひら",
        ["Surprised"] = "びっくり",
        ["SlenderBody"] = "ほっそり",
        ["Blink"] = "まばたき",
        ["WiderBody"] = "むっちり",
        ["Purple"] = "パープル",
        ["Sideburn"] = "モミアゲ",
        ["Amber"] = "アンバー",
        ["Armor"] = "アーマー",
        ["Yellow"] = "黄色",
        ["Wink"] = "ウィンク",
        ["Waist"] = "腰",
        ["Apron"] = "エプロン",
        ["Olive"] = "オリーブ",
        ["Overcoat"] = "オーバー",
        ["ColorVariations"] = "カラバリ",
        ["Cap"] = "キャップ",
        ["Crotch"] = "クロッチ",
        ["Green"] = "緑",
        ["Groove"] = "グルーブ",
        ["Group"] = "グループ",
        ["Sandals"] = "サンダル",
        ["Siesta"] = "シエスタ",
        ["Shorts"] = "ショーツ",
        ["Jean"] = "ジーンズ",
        ["SkirtSide"] = "スカト横",
        ["Skirt"] = "スカト",
        ["Scarf"] = "マフラー",
        ["Spectrum"] = "スペアナ",
        ["Sports"] = "スポーツ",
        ["Slime"] = "スライム",
        ["Slippers"] = "スリッパ",
        ["Center"] = "央",
        ["Sweater"] = "セーター",
        ["Chain"] = "鎖",
        ["Vest"] = "チョッキ",
        ["Twintail"] = "ツインテ",
        ["Cards"] = "トランプ",
        ["Necktie"] = "ネクタイ",
        ["Buckle"] = "バックル",
        ["Bunny"] = "兎",
        ["Pajamas"] = "パジャマ",
        ["Pansy"] = "パンジー",
        ["Pantyhose"] = "パンスト",
        ["Blouse"] = "ブラウス",
        ["Black"] = "黒",
        ["Briefs"] = "ブリーフ",
        ["Blazer"] = "ブレザー",
        ["Bronze"] = "ブロンズ",
        ["Blond"] = "ブロンド",
        ["Brooch"] = "ブロチ",
        ["Beige"] = "ベージュ",
        ["White"] = "白",
        ["Bordeaux"] = "ボルドー",
        ["Magenta"] = "マゼンタ",
        ["Maroon"] = "マルーン",
        ["Tape"] = "メジャー",
        ["Rivet"] = "リベット",
        ["Braid"] = "三つ編み",
        ["RoundedTips"] = "先端丸め",
        ["ParentNode"] = "全ての親",
        ["Hatsune Miku"] = "初音ミク",
        ["PowerUp"] = "力アップ",
        ["ReflectionLower"] = "反射下げ",
        ["Shiki Eiki"] = "四季映姫",
        ["PreventSagging"] = "れ防止",
        ["Anger"] = "怒り漫符",
        ["ControlNode"] = "操作中心",
        ["CostumeColor"] = "服色調整",
        ["Bust_guard"] = "胸押さえ",
        ["ChainMovement"] = "鎖移動",
        ["HairColor"] = "髪色調整",
        ["Swirl"] = "グルグル",
        ["Mad"] = "くやしい",
        ["Cross Star"] = "シイタケ",
        ["Oiled"] = "ヌル",
        ["Translucent"] = "透ジャ",
        ["Zip"] = "ジップ",
        ["Bandage"] = "絆創膏",
        ["Dummy"] = "ダミー",
        ["Oh no!"] = "あぅう",
        ["Antenna"] = "触覚",
        ["Clothes"] = "服",
        ["Cry"] = "泣き",
        ["Coat"] = "上着",
        ["Pigtail"] = "おさげ",
        ["Roar"] = "がおー",
        ["Gloom"] = "ガーン",
        ["Kimono"] = "着物",
        ["FemaleNinja"] = "くノ一",
        ["Underwear"] = "下着",
        ["Stare"] = "じと目",
        ["Suit"] = "背広",
        ["Mechanism"] = "だくみ",
        ["TehHeh"] = "てへ",
        ["Tears"] = "涙",
        ["Calm"] = "和み",
        ["Coloring"] = "なぬっ",
        ["Confuse"] = "なぬ！",
        ["Lick"] = "舐",
        ["Cheerful"] = "にこり",
        ["Wrinkle"] = "にしわ",
        ["Grin"] = "にやり",
        ["Heart"] = "ハート",
        ["Hachu"] = "はちゅ",
        ["Pants"] = "パンツ",
        ["Sleepy"] = "ふにゃ",
        ["Fuun"] = "ふーん",
        ["Hat"] = "帽子",
        ["Eyelash"] = "まつげ",
        ["Swimsuit"] = "水着",
        ["Glasses"] = "眼鏡",
        ["SummerKimono"] = "浴衣",
        ["Ring"] = "指輪",
        ["Access"] = "アクセ",
        ["Duck"] = "アヒル",
        ["IhHiHi"] = "イヒヒ",
        ["Ears"] = "耳",
        ["Leg"] = "足",
        ["Edge"] = "エッジ",
        ["Cuff"] = "カフス",
        ["Khaki"] = "カーキ",
        ["Girl"] = "ガール",
        ["Cork"] = "コルク",
        ["Cord"] = "コード",
        ["Samba"] = "サンバ",
        ["Cyan"] = "シアン",
        ["Seam"] = "シーム",
        ["Trousers"] = "ズボン",
        ["Set"] = "セット",
        ["Sepia"] = "セピア",
        ["Tights"] = "タイツ",
        ["Back"] = "背",
        ["Badge"] = "バッジ",
        ["Band"] = "帯",
        ["Part"] = "部",
        ["Hip"] = "ヒップ",
        ["Bikini"] = "ビキニ",
        ["Pink"] = "桃",
        ["Peach"] = "ピーチ",
        ["Frill"] = "フリル",
        ["Brim"] = "ブリム",
        ["Blue"] = "青",
        ["Boots"] = "ブツ",
        ["Belt"] = "ベルト",
        ["Button"] = "ボタン",
        ["Body"] = "身",
        ["Bottom"] = "ボトム",
        ["Bone"] = "骨",
        ["Really"] = "マジデ",
        ["Cloak"] = "マント",
        ["Meiko"] = "メイコ",
        ["Maid"] = "メイド",
        ["Morph"] = "モーフ",
        ["Mauve"] = "モーブ",
        ["Ribbon"] = "リボン",
        ["Red"] = "赤",
        ["Rose"] = "ローズ",
        ["UpperBody"] = "上半身",
        ["Chin"] = "下顎",
        ["LowerBody"] = "下半身",
        ["Bad mood"] = "不機嫌",
        ["Double"] = "八重",
        ["IndexFinger"] = "人指",
        ["Taper"] = "先細り",
        ["Izayoi"] = "十六夜",
        ["Sunflower"] = "向日葵",
        ["FemaleWarrior"] = "女戦士",
        ["Together"] = "寄せる",
        ["Koakuma"] = "小悪魔",
        ["Onozuka"] = "小野塚",
        ["Yuyuko"] = "幽々子",
        ["Sad"] = "悲しい",
        ["ChangeColor"] = "色変え",
        ["CasualClothes"] = "様私服",
        ["Fasteners"] = "止め具",
        ["SwallowTailCoat"] = "燕尾服",
        ["Serious"] = "真面",
        ["Kanako"] = "神奈子",
        ["Move"] = "移動",
        ["String"] = "紐",
        ["Tighten"] = "細める",
        ["EarMovement"] = "耳移動",
        ["Bust_support"] = "胸補助",
        ["Saigyouji"] = "西行寺",
        ["Spread"] = "見開く",
        ["Pale"] = "青ざめ",
        ["Leather"] = "革",
        ["RubberBand"] = "髪留め",
        ["Slant"] = "つり",
        ["Wow"] = "うわぁ",
        ["Mark"] = "マーク",
        ["Glue"] = "ぐぎぎ",
        ["Slurping"] = "しらけ",
        ["Well"] = "うへぁ",
        ["Jaw"] = "顎",
        ["Arm"] = "腕",
        ["Uueh"] = "うへ",
        ["Collar"] = "襟",
        ["e-"] = "えー",
        ["Ugh"] = "くっ",
        ["Shoes"] = "靴",
        ["Right"] = "右",
        ["Left"] = "左",
        ["Tips"] = "点",
        ["Tooth"] = "牙",
        ["Sushi"] = "すじ",
        ["LowerClothes"] = "裾",
        ["Sleeve"] = "袖",
        ["Falcon"] = "たか",
        ["Droopy"] = "たれ",
        ["Toe"] = "つま",
        ["Thorn"] = "棘",
        ["None"] = "無し",
        ["Haa"] = "はぁ",
        ["Close><"] = "はぅ",
        ["Knee"] = "ひざ",
        ["Elbow"] = "肘",
        ["Inflate"] = "ぷぅ",
        ["Grow"] = "ぷく",
        ["TongueOut"] = "べー",
        ["Cruciform"] = "ぽっ",
        ["Eee"] = "イー",
        ["Off"] = "オフ",
        ["Looseness"] = "ガタ",
        ["Tan"] = "タン",
        ["Hair"] = "髪",
        ["Buff"] = "バフ",
        ["Spotted"] = "ブチ",
        ["Behh"] = "ベー",
        ["Miku"] = "ミク",
        ["Lower"] = "下",
        ["Raise"] = "上げ",
        ["Upper"] = "上",
        ["Dissatisfied"] = "不満",
        ["Eyes"] = "両目",
        ["MiddleFinger"] = "中指",
        ["Attachment"] = "付",
        ["Bodyu"] = "体上",
        ["Bodyl"] = "体下",
        ["Yasaka"] = "八坂",
        ["Yagokoro"] = "八意",
        ["Yakumo"] = "八雲",
        ["Hexagon"] = "六角",
        ["FrontHair"] = "前髪",
        ["Yuugi"] = "勇儀",
        ["Hide"] = "隠",
        ["RightHand"] = "右ハ",
        ["Sunrise"] = "向日",
        ["Amazement"] = "呆れ",
        ["Sakuya"] = "咲夜",
        ["Bite"] = "噛む",
        ["Apparatus"] = "器具",
        ["Rotation"] = "回転",
        ["Troubled"] = "困り",
        ["Sadness"] = "困る",
        ["Base"] = "根",
        ["Wider"] = "太い",
        ["FemalePriest"] = "女僧",
        ["WiseWoman"] = "女賢",
        ["Learning"] = "学迷",
        ["LittleFinger"] = "小指",
        ["Komachi"] = "小町",
        ["LeftHand"] = "左ハ",
        ["Yuuka"] = "幽香",
        ["Widen"] = "広げ",
        ["Behind"] = "後ろ",
        ["Angry"] = "怒",
        ["GetAngry"] = "怒る",
        ["Emotion"] = "感情",
        ["Grieving"] = "憂い",
        ["Warrior"] = "戦士",
        ["Wrist"] = "手首",
        ["Shake"] = "揺",
        ["New"] = "新規",
        ["Color"] = "色",
        ["Hoshiguma"] = "星熊",
        ["Princess"] = "映姫",
        ["Deep"] = "暗く",
        ["Material"] = "材質",
        ["Blush"] = "染",
        ["ChangeColoredShapes"] = "模様",
        ["SideHair"] = "横髪",
        ["Eirin"] = "永琳",
        ["Puffy Eyes"] = "涙袋",
        ["Measurement"] = "測定",
        ["Collapse"] = "潰れ",
        ["Physics"] = "物理",
        ["Narrowly"] = "狭く",
        ["Byakuren"] = "白蓮",
        ["Eyebrow"] = "眉",
        ["Wear"] = "着",
        ["Pupil"] = "瞳",
        ["Blink Happy"] = "笑い",
        ["Laugh"] = "笑う",
        ["Thinner"] = "薄い",
        ["Thin Eyebrows"] = "細眉",
        ["Gentleman"] = "紳士",
        ["Scroll"] = "経巻",
        ["Gun"] = "線銃",
        ["Braids"] = "編改",
        ["Locations"] = "置置",
        ["Meiling"] = "美鈴",
        ["Cordon"] = "腰紐",
        ["Stage"] = "舞台",
        ["Leaves"] = "葉収",
        ["RingFinger"] = "薬指",
        ["Costume"] = "衣装",
        ["Expressions"] = "表情",
        ["Aux"] = "補助",
        ["Thumb"] = "親指",
        ["Angle"] = "角度",
        ["Expand"] = "拡",
        ["Adjustment"] = "調整",
        ["Pastie"] = "貼",
        ["WiseMan"] = "賢者",
        ["Ankle"] = "足首",
        ["MilitaryCap"] = "軍帽",
        ["MilitaryUniform"] = "軍装",
        ["LightClothing"] = "軽装",
        ["Lightweight"] = "軽量",
        ["Contour"] = "輪郭",
        ["Append"] = "追加",
        ["Transparent"] = "透",
        ["Connection"] = "結",
        ["Parts"] = "部部",
        ["Metal"] = "金属",
        ["Clavicle"] = "鎖骨",
        ["Open"] = "開",
        ["Dark"] = "闇色",
        ["Blue green"] = "青色",
        ["Kazami"] = "風見",
        ["Accessory"] = "飾り",
        ["IK"] = "ＩＫ",
        ["Glaring"] = "睨む",
        ["Both"] = "両八",
        ["Star"] = "星",
        ["Ear"] = "みみ",
        ["ω□"] = "ω□",
        ["~"] = "～",
        ["ー"] = "ー",
        ["ω"] = "ω",
        ["※"] = "※",
        ["∧"] = "∧",
        ["□"] = "□",
        ["▲"] = "▲",
        ["○"] = "○",
        ["●"] = "●",
        [">"] = "＞",
        ["<"] = "＜",
        [""] = "っ",
        ["@"] = "◎",
        ["A"] = "Ａ",
        ["I"] = "Ｉ",
        ["U"] = "う",
        ["E"] = "え",
        ["O"] = "Ｏ",
        ["Hmm"] = "ん",
        ["no"] = "の",
        ["FacialExpression"] = "び",
        ["Beh"] = "べ",
        ["wo"] = "を",
        ["Higher"] = "ハ",
        ["Wa"] = "ワ",
        ["*"] = "・",
        ["One"] = "一",
        ["Middle"] = "中",
        ["Circle"] = "円",
        ["Two"] = "二",
        ["Other"] = "他",
        ["Extend"] = "伸",
        ["Location"] = "置",
        ["Origin"] = "元",
        ["Tip"] = "尖",
        ["Light"] = "光",
        ["Six"] = "六",
        ["Inside"] = "内",
        ["Out"] = "出",
        ["Front"] = "前",
        ["Sword"] = "剣",
        ["Half"] = "半",
        ["Thick"] = "厚",
        ["Mouth"] = "口",
        ["Lips"] = "唇",
        ["Vertical"] = "縦",
        ["Type"] = "類",
        ["Category"] = "基",
        ["Change"] = "変",
        ["Outside"] = "外",
        ["Big"] = "大",
        ["Wide"] = "広",
        ["Character"] = "字",
        ["Gem"] = "宝",
        ["Small"] = "貧",
        ["Butt"] = "尻",
        ["Tail"] = "尾",
        ["Difference"] = "差",
        ["Book"] = "本",
        ["Force"] = "強",
        ["ColorScheme"] = "彩",
        ["Evil"] = "悪",
        ["Love"] = "愛",
        ["Return"] = "戻",
        ["Hand"] = "手",
        ["TieFasten"] = "括",
        ["Finger"] = "指",
        ["Twist"] = "捩",
        ["Cherry"] = "桜",
        ["Side"] = "横",
        ["Teeth"] = "歯",
        ["Strand"] = "毛",
        ["Water"] = "水",
        ["Sweat"] = "汗",
        ["Nothing"] = "無",
        ["Swallow"] = "燕",
        ["Object"] = "物",
        ["Narrow"] = "狭",
        ["Ball"] = "球",
        ["Bare"] = "裸",
        ["Eye"] = "眼",
        ["Stone"] = "石",
        ["End"] = "端",
        ["LOL"] = "笑",
        ["Marks"] = "符",
        ["Muscle"] = "筋",
        ["Hong"] = "紅",
        ["Yukari"] = "紫",
        ["Thin"] = "薄",
        ["Net"] = "網",
        ["Wing"] = "羽",
        ["Hijiri"] = "聖",
        ["Skin"] = "肌",
        ["Shoulder"] = "肩",
        ["Breast"] = "胸",
        ["Shin"] = "脛",
        ["Armpit"] = "腋",
        ["Belly"] = "腹",
        ["Thigh"] = "腿",
        ["Tongue"] = "舌",
        ["Dance"] = "踊",
        ["Flower"] = "花",
        ["Leaf"] = "葉",
        ["Hollyhock"] = "葵",
        ["Lotus"] = "蓮",
        ["Ran"] = "藍",
        ["Rainbow"] = "虹",
        ["Snake"] = "蛇",
        ["Increase"] = "補",
        ["Parent"] = "親",
        ["Horn"] = "角",
        ["Army"] = "軍",
        ["Axis"] = "軸",
        ["Circles"] = "輪",
        ["Over"] = "過",
        ["Cone"] = "錐",
        ["ChainStraps"] = "鎧",
        ["Interval"] = "間",
        ["Not"] = "非",
        ["Top"] = "頂",
        ["Cheek"] = "頬",
        ["Head"] = "頭",
        ["Face"] = "顔",
        ["Neck"] = "首",
        ["Demon"] = "魔",
    };

    private List<string> excludeMorphs = new List<string>()
    {
        // Common non-blendshape morphs to exclude
        // Add more as needed
    };
    // private List<uint> excludeHashes = new List<uint>();
    private List<uint> excludeHashes = new List<uint>()
    {
        // Known problematic hashes to exclude
        1968285791,
        3655657299,
        3956442577
    };
    // CRC map: hashedValue -> desired propertyName (e.g. "blendShape.まばたき")
    private Dictionary<uint, string> crcMap = new Dictionary<uint, string>();

    // CRC table for fast compute
    private static readonly uint[] crcTable = BuildCrcTable();

    [MenuItem("AnimTools/Blendshape Restorer")]
    public static void ShowWindow()
    {
        GetWindow<BlendshapeCurveRestorer>("Blendshape Restorer");
    }

    private void OnGUI()
    {
        GUILayout.Label("BlendShape Curve Restorer", EditorStyles.boldLabel);

        EditorGUILayout.Space();
        sourceClip = (AnimationClip)EditorGUILayout.ObjectField("Source AnimationClip", sourceClip, typeof(AnimationClip), false);
        saveSuffix = EditorGUILayout.TextField("Save Suffix", saveSuffix);

        EditorGUILayout.Space();
        GUILayout.Label("Morph Candidates (editable):", EditorStyles.label);

        scrollPos = EditorGUILayout.BeginScrollView(scrollPos, GUILayout.Height(220));
        for (int i = 0; i < morphCandidates.Count; i++)
        {
            EditorGUILayout.BeginHorizontal();
            morphCandidates[i] = EditorGUILayout.TextField(morphCandidates[i]);
            if (GUILayout.Button("−", GUILayout.Width(24)))
            {
                morphCandidates.RemoveAt(i);
                i--;
            }
            EditorGUILayout.EndHorizontal();
        }
        EditorGUILayout.EndScrollView();

        if (GUILayout.Button("Add Candidate")) morphCandidates.Add("");

        EditorGUILayout.Space();
        if (GUILayout.Button("Build CRC Map (preview)"))
        {
            BuildCrcMap();
            Debug.Log($"[BlendshapeRestorer] crcMap built with {crcMap.Count} entries.");
        }

        EditorGUILayout.Space();
        if (GUILayout.Button("Restore Selected Clip"))
        {
            if (sourceClip == null)
            {
                EditorUtility.DisplayDialog("Error", "Please select an AnimationClip first.", "OK");
            }
            else
            {
                BuildCrcMap();
                RestoreClip(sourceClip, saveSuffix);
            }
        }
    }

    private void BuildCrcMap()
    {
        crcMap.Clear();

        foreach (var m in morphCandidates)
        {
            if (string.IsNullOrEmpty(m)) continue;

            // We want the final property name to be: "blendShape.<morph>"
            string desired = $"blendShape.{m}";

            // Variant 1: CRC of "blendShape.<morph>" (common if Unity hashed full property name)
            uint crc1 = ComputeCrc32Standard(Encoding.UTF8.GetBytes(desired));
            if (!crcMap.ContainsKey(crc1)) crcMap[crc1] = desired;

            // Variant 2: CRC of just "<morph>" (some serializers/hashers only hashed the plain morph name)
            uint crc2 = ComputeCrc32Standard(Encoding.UTF8.GetBytes(m));
            if (!crcMap.ContainsKey(crc2)) crcMap[crc2] = desired;

            // Variant 3: alternative variant without final XOR (robustness: some tools differ)
            uint crc3 = ComputeCrc32NoXor(Encoding.UTF8.GetBytes(desired));
            if (!crcMap.ContainsKey(crc3)) crcMap[crc3] = desired;

            // uint crc4 = ComputeCrc32NoXor(Encoding.UTF8.GetBytes(m));
            // if (!crcMap.ContainsKey(crc4)) crcMap[crc4] = desired;

            // Note: collisions are rare for reasonable lists; if collision happens
            // the first inserted mapping is kept.
        }
    }

    public void RestoreClip(AnimationClip clip, string suffix)
    {
        string srcPath = AssetDatabase.GetAssetPath(clip);
        if (string.IsNullOrEmpty(srcPath))
        {
            EditorUtility.DisplayDialog("Error", "Can't determine asset path for selected clip.", "OK");
            return;
        }

        string dir = Path.GetDirectoryName(srcPath);
        string name = Path.GetFileNameWithoutExtension(srcPath);
        string ext = Path.GetExtension(srcPath);
        string destPath = Path.Combine(dir, name + suffix + ext).Replace("\\", "/");

        // If file exists, ask user
        if (AssetDatabase.LoadAssetAtPath<AnimationClip>(destPath) != null)
        {
            if (!EditorUtility.DisplayDialog("Overwrite?", $"Destination {destPath} already exists. Overwrite?", "Yes", "Cancel"))
            {
                Debug.Log("[BlendshapeRestorer] Operation cancelled by user.");
                return;
            }
            AssetDatabase.DeleteAsset(destPath);
        }

        // Copy asset to create a working copy
        if (!AssetDatabase.CopyAsset(srcPath, destPath))
        {
            EditorUtility.DisplayDialog("Error", $"Failed to copy asset to {destPath}", "OK");
            return;
        }
        AssetDatabase.ImportAsset(destPath);
        AssetDatabase.Refresh();

        var newClip = AssetDatabase.LoadAssetAtPath<AnimationClip>(destPath);
        if (newClip == null)
        {
            EditorUtility.DisplayDialog("Error", "Failed to load copied animation clip.", "OK");
            return;
        }

        int replacedCount = 0;
        var unmapped = new HashSet<uint>();

        // Process float (regular) curves
        var floatBindings = AnimationUtility.GetCurveBindings(newClip).ToList();
        foreach (var b in floatBindings)
        {
            string prop = b.propertyName;
            uint? foundHash = TryExtractFirstUInt(prop);
            if (!foundHash.HasValue) continue;

            uint h = foundHash.Value;

            // Skip if hash is in exclude list
            if (excludeHashes.Contains(h))
            {
                AnimationUtility.SetEditorCurve(newClip, b, null);
                continue;
            }

            if (crcMap.TryGetValue(h, out string newPropName))
            {
                // Check for alias in morphAlias dictionary
                string newMorphName = newPropName.Substring(11); // Remove "blendShape." prefix
                if (morphAlias.TryGetValue(newMorphName, out string aliasPropName))
                {
                    newMorphName = "blendShape." + aliasPropName;
                }
                else
                {
                    newMorphName = newPropName; // Keep original if no alias
                }

                // If already the target name, skip
                if (prop == newMorphName) continue;

                var curve = AnimationUtility.GetEditorCurve(newClip, b);
                var newBinding = b;
                newBinding.propertyName = newMorphName;

                // Set new curve and remove old one
                AnimationUtility.SetEditorCurve(newClip, newBinding, curve);
                AnimationUtility.SetEditorCurve(newClip, b, null);
                replacedCount++;
            }
            else
            {
                unmapped.Add(h);
            }
        }

        // Process object-reference curves (just in case)
        var objBindings = AnimationUtility.GetObjectReferenceCurveBindings(newClip).ToList();
        foreach (var b in objBindings)
        {
            string prop = b.propertyName;
            uint? foundHash = TryExtractFirstUInt(prop);
            if (!foundHash.HasValue) continue;

            uint h = foundHash.Value;

            // Skip if hash is in exclude list
            if (excludeHashes.Contains(h))
            {
                AnimationUtility.SetObjectReferenceCurve(newClip, b, null);
                continue;
            }

            if (crcMap.TryGetValue(h, out string newPropName))
            {
                // Check for alias in morphAlias dictionary
                if (morphAlias.TryGetValue(newPropName, out string aliasPropName))
                {
                    newPropName = aliasPropName;
                }

                // If already the target name, skip
                if (prop == newPropName) continue;

                var keyframes = AnimationUtility.GetObjectReferenceCurve(newClip, b);
                var newBinding = b;
                newBinding.propertyName = newPropName;

                AnimationUtility.SetObjectReferenceCurve(newClip, newBinding, keyframes);
                AnimationUtility.SetObjectReferenceCurve(newClip, b, null);
                replacedCount++;
            }
            else
            {
                unmapped.Add(h);
            }
        }

        AssetDatabase.SaveAssets();
        AssetDatabase.ImportAsset(destPath);
        AssetDatabase.Refresh();

        // Show result dialog + log unmapped
        string msg = $"Done. Replaced {replacedCount} curve(s).\nUnmapped unique hashes: {unmapped.Count}.";
        EditorUtility.DisplayDialog("Blendshape Restorer", msg, "OK");

        if (unmapped.Count > 0)
        {
            Debug.Log("[BlendshapeRestorer] Unmapped CRC32 values (add these morph names to candidate list if you know them):");
            foreach (var u in unmapped)
            {
                Debug.Log(u + "  (0x" + u.ToString("X8") + ")");
            }
        }

        Debug.Log($"[BlendshapeRestorer] Restored clip saved at: {destPath}");
        Selection.activeObject = newClip;
    }

    // Try to extract the first run of digits from a property string
    private static uint? TryExtractFirstUInt(string s)
    {
        if (string.IsNullOrEmpty(s)) return null;
        var m = Regex.Match(s, @"\d+");
        if (!m.Success) return null;
        if (uint.TryParse(m.Value, out uint val)) return val;
        return null;
    }

    #region CRC helpers

    // Build CRC table for polynomial 0xEDB88320
    private static uint[] BuildCrcTable()
    {
        uint poly = 0xEDB88320;
        uint[] table = new uint[256];
        for (uint i = 0; i < 256; ++i)
        {
            uint crc = i;
            for (int j = 0; j < 8; ++j)
            {
                if ((crc & 1) == 1) crc = (crc >> 1) ^ poly;
                else crc >>= 1;
            }
            table[i] = crc;
        }
        return table;
    }

    // Standard CRC32 (initial 0xFFFFFFFF, final XOR 0xFFFFFFFF) — common "CRC-32" implementation
    private static uint ComputeCrc32Standard(byte[] bytes)
    {
        uint crc = 0xFFFFFFFF;
        foreach (var b in bytes)
        {
            crc = (crc >> 8) ^ crcTable[(crc ^ b) & 0xFF];
        }
        return crc ^ 0xFFFFFFFF;
    }

    // Alternative variant WITHOUT final XOR (some tools differ) — included for robustness
    private static uint ComputeCrc32NoXor(byte[] bytes)
    {
        uint crc = 0;
        foreach (var b in bytes)
        {
            crc = (crc >> 8) ^ crcTable[(crc ^ b) & 0xFF];
        }
        return crc;
    }

    #endregion
}
