name: Build and Release UnityPackage

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Export Unity Package
        uses: webbertakken/unity-builder@v2
        with:
          unityVersion: 2022.3.54f1  # 替换为你的 Unity 版本
          targetPlatform: StandaloneWindows
          buildMethod: UnityEditor.PackageManager.Client.ExportPackage
          packagePath: Assets/AnimConverter  # 替换为你的工具包路径
          outputPath: build/AnimConverter.unitypackage
          
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/AnimConverter.unitypackage
          asset_name: AnimConverter.unitypackage
          asset_content_type: application/octet-stream